name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.5'
        
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Download dependencies
      run: go mod download
      
    - name: Run tests
      run: go test ./...
      
    - name: Build for multiple platforms
      run: |
        # Create release directory
        mkdir -p release

        go mod tidy
        
        # Build for different platforms
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o release/monday-cli-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o release/monday-cli-linux-arm64 .
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o release/monday-cli-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o release/monday-cli-darwin-arm64 .
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o release/monday-cli-windows-amd64.exe .
        GOOS=windows GOARCH=arm64 go build -ldflags="-s -w" -o release/monday-cli-windows-arm64.exe .
        
    - name: Create checksums
      run: |
        cd release
        sha256sum * > checksums.txt
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: monday-cli-binaries
        path: release/
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: release/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
